repos:
  init:
    url: https://github.com/kangu/CouchFusion-BaseLayers.git
    branch: main
    protocol: https
    authPrompt: false
  new:
    url: https://github.com/kangu/CouchFusion-StarterApp.git
    branch: main
    protocol: https
    authPrompt: false
  create_layer:
    url: https://github.com/kangu/CouchFusion-StarterLayer.git
    branch: main
    protocol: https
    authPrompt: false
modules:
  analytics:
    description: Analytics tracking utilities
    extends: "@layers/analytics"
  auth:
    description: Authentication middleware and helpers
    extends: "@layers/auth"
  content:
    description: Content management utilities
    extends: "@layers/content"
  database:
    description: Raw database utilities
    extends: "@layers/database"
  imagekit:
    description: ImageKit utilities for managing images
    extends: "@layers/imagekit"
  lightning:
    description: Support for generating lightning network invoices
    extends: "@layers/lightning"
  orders:
    description: Support for managing products and orders
    extends: "@layers/orders"
workspace:
  defaultRoot: "."
prompts:
  defaultLayerSelection:
    - analytics
    - auth
    - content
